### ISSUE TITLE
When my database is not connected.

### ISSUE THREAD

**Issue by BrandonNolte** [BrandonNolte/listdir#4]
It looks like the issue is the db is is being pointed to which is not running or simply misconfigured. Interestingly enough failing on the insert_one. 

^CTraceback (most recent call last):
  File "mongolist.py", line 48, in <module>
    format_and_report(file,is_dir)
  File "mongolist.py", line 35, in format_and_report
    post = collection.insert_one(formattedfiles)
  File "build/bdist.macosx-10.11-intel/egg/pymongo/collection.py", line 654, in insert_one
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.macosx-10.11-intel/egg/pymongo/mongo_client.py", line 823, in _get_socket
  File "build/bdist.macosx-10.11-intel/egg/pymongo/topology.py", line 214, in select_server
  File "build/bdist.macosx-10.11-intel/egg/pymongo/topology.py", line 198, in select_servers
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by BrandonNolte** [comment]
There is also an issue with the "mongodb_validate".

**Comment by BrandonNolte** [comment]
Looks like the initial issue is "localhost" is spelled incorrectly. 


[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> import pprint
>>> import json
>>> import pymongo
>>> import time
>>> from pymongo import MongoClient
>>> #from bson import BSON
... #from bson import json_util
... 
client_uri = "mongodb://lcalhost:27017"
>>> 
>>> def mongodb_validate( client_uri ):
...     try:
...         return pymongo.MongoClient( client_uri )
...     except pymongo.errors.connectionFailure:
...         print "I have failed to connect to mongo {}".format( client_uri )
...         sys.exit(1)
...     return
... mongodb_validate( client_uri )
  File "<stdin>", line 8
    mongodb_validate( client_uri )
                   ^
SyntaxError: invalid syntax
